export const ERR_CODES = {
  NO_TOKEN_ERR: "NO_TOKEN_ERR",
  NO_QUERY_ERR: "NO_QUERY_ERR",
  NO_PASSWORD_ERR: "NO_PASSWORD_ERR",
  INVALID_PARAM_ERR: "INVALID_PARAM_ERR",
  INVALID_PASSWORD_ERR: "INVALID_PASSWORD_ERR",
  INVALID_VERIFICATION_TOKEN_ERR: "INVALID_VERIFICATION_TOKEN_ERR",
  TO_MANY_ROWS_ERR: "TO_MANY_ROWS_ERR",
  UNSUPPORTED_QUERY_ERR: "UNSUPPORTED_QUERY_ERR",
  INTERNAL_SERVER_ERR: "INTERNAL_SERVER_ERR",
};
