version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: SA
      MONGO_INITDB_ROOT_PASSWORD: Password123!
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network

volumes:
  mongo_data:

networks:
  mongo_network:
    driver: bridge
